name: Build ZMK firmware & draw keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
